name: Build Pages
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ðŸ›Žï¸
      uses: actions/checkout@v2
    - name: Setup NodeJS ðŸ’Ž
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Download Latest GitHub Profile â¬‡ï¸
      uses: wei/curl@master
      with:
        args: >
          -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/users/JeffResc/repos --create-dirs --output ${{ GITHUB_WORKSPACE }}/content/github_projects.json
    - name: Install Dependencies & Build Project ðŸ”§
      run: |
        npm install
        npm run build
