name: Build and Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ðŸ›Žï¸
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Setup NodeJS ðŸ’Ž
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install Dependencies & Build Project ðŸ”§
      run: |
        npm install
        npm run build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download Latest GitHub Profile â¬‡ï¸
      uses: wei/curl@master
      with:
        args: >
          -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/users/JeffResc/repos --output content/github_projects.json
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        git-config-name: Jeff Rescignano (Auto Deploy)
        git-config-email: jeff@jeffresc.dev
        commit-message: Auto Deploy From GitHub Actions
        single-commit: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: public
        clean: true
